name: Feature Request
description: Propose an enhancement
title: '[feature] '
labels: ['enhancement', 'triage']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user or operational problem are we solving?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the desired behavior and constraints
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
